services:
  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: facieai-backend
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    container_name: facieai-bot
    environment:
      BACKEND_BASE_URL: http://backend:8000
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
