### Створити нового друга
POST http://localhost:8000/friends/

# Не вказуємо Content-Type, HTTP Client сам додасть multipart/form-data
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="name"

Alice
--boundary
Content-Disposition: form-data; name="profession"

Engineer
--boundary
Content-Disposition: form-data; name="profession_description"

Loves coding and robotics
--boundary
Content-Disposition: form-data; name="photo"; filename="photo.jpg"
Content-Type: image/jpeg

< ./photo.jpg
--boundary--
